"""
some user defined exception here.
"""


class CustomException(Exception):
    pass


class ArgumentsError(CustomException):
    pass
